server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
      url: jdbc:mariadb://database-2.cksp68xdflw4.ap-northeast-2.rds.amazonaws.com:3306/hehe
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234
   
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  output: 
    ansi:
      enabled: always

file:
  path: /home/ubuntu/hehe/